logging:
  level:
    #feign日志配置
    pers.mine.nookblog.rpc.*: DEBUG
#spring MSQL数据库
spring:
  devtools:
    restart:
      enabled: true
mine-info:
  userName: 临时用户
  userID: minenook
  password: A6A6ED6D88F078A196A898769940DA2F
mine:
  feign:
    loglevel: FULL